jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/parcel-tracker:${{ github.ref_name }} .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/parcel-tracker:${{ github.ref_name }}